### ISSUE TITLE
api.Auth.ValidateAPIKey() - Status = WaitingForActivation

### ISSUE THREAD

**Issue by MikolasFromm** [OkGoDoIt/OpenAI-API-dotnet#109]
Running:
OpenAPI-API-dotnet 1.7.2

I've started testing your API for creating requests to OpenAI API, but I always get an empty response.
Therefore I have tried to call `ValidateAPIKey()` in order to check whats wrong with my client, because non of the examples given in the Readme.md seems to work.

```
var api = new OpenAIAPI(new APIAuthentication(Secrets.Credentials.PersonalApiKey));
var validation = api.Auth.ValidateAPIKey();
var chat = api.Chat.CreateConversation();
```

Surprisingly, the `api.Auth.ValidateAPIKey()` response looks like this:
`Id = 23, Status = WaitingForActivation, Method = "{null}", Result = "{Not yet computed}"`

Any hints how to get the API key activated?

Thanks!

**Comment by AgentBelfort** [comment]
you should use await:
var validation = await api.Auth.ValidateAPIKey();

**Comment by MikolasFromm** [comment]
Thanks for the response. When `await` used, the appliaction terminates just after that and no validation status is given. :/

```
var api = new OpenAIAPI(new APIAuthentication(Secrets.Credentials.PersonalApiKey));
var validation = await api.Auth.ValidateAPIKey();

// this is where the app terminates

Console.WriteLine("milestsone"); // this never gets called
Console.WriteLine(validation); // nor this
```

**Comment by AgentBelfort** [comment]
It works in my code:
![image](https://user-images.githubusercontent.com/77501668/230414180-e9f9d378-6585-4a26-a976-ae5f57f6897c.png)
maybe you should try to update library

**Comment by MikolasFromm** [comment]
Thanks for the reply. It was actually very simple, but maybe someone will have the same problem as me.

`static void Main(string[] args)` should have been replaced by `static async Task Main(string[] args)`.
After that, the validation is successful and the API works well. :)
