### ISSUE TITLE
codex support

### ISSUE THREAD

**Issue by Licantrop0** [OkGoDoIt/OpenAI-API-dotnet#12]
Hi, I see that in some examples (https://beta.openai.com/examples/default-sql-translate) the davinci-codex is set as an engine, but I can't set it with this SDK.

is there any workaround for this?

**Comment by WilliamWelsh** [comment]
Do you have access to codex? I think this repository isn't maintained anymore so I started my own [fork](https://github.com/WilliamWelsh/OpenAI.Net). It has `davinci-codex` and `cushman-codex`, but I am unable to test them as I don't have access.

**Comment by benedlore** [comment]
@Licantrop0 Can you share or give me some assistance with C# wrapper for Codex?

**Comment by Licantrop0** [comment]
@benedlore I just published this for you: https://gist.github.com/Licantrop0/115f7f0280e865c69e3849c8a14989dc let me know if you have questions.

**Comment by gotmike** [comment]
most recent models have been added in: https://github.com/OkGoDoIt/OpenAI-API-dotnet/commit/f4d9d9d1b9885176948967f21074ad1ebe00331a
