### ISSUE TITLE
Q&A Request

### ISSUE THREAD

**Issue by Birillox** [OkGoDoIt/OpenAI-API-dotnet#16]
I can't see out how to make a script to use the Q&A portion.. can you help me?

**Comment by TheBarret** [comment]
I like to know this too, thanks! :D

**Comment by OkGoDoIt** [comment]
Are you referring to the ChatGPT-style interaction?  There is no API access for that yet, although OpenAI says it's coming soon.

**Comment by TheBarret** [comment]
> @Birillox / @TheBarret -- can you clarify the question a bit more? i'm not sure exactly what you are asking...
You can disregard that, I forgot all about it. my bad!
