### ISSUE TITLE
Image Generation: DALL-E-3

### ISSUE THREAD

**Issue by elango-kamatchi** [OkGoDoIt/OpenAI-API-dotnet#180]
How can we create image with version DALL-E-3?. Seems CreateImageAsync method, we don't have select of which version like DALL-E-2 or DALL-E-3.

**Comment by lofcz** [comment]
Dalle3 is supported in this fork: https://github.com/lofcz/OpenAiNg

**Comment by elango-kamatchi** [comment]
Hi lofcz, OpenAiNg supports only .NET Core >= 6.0, but my project is .NET Framework and version 4.7.2. So we cannot install OpenAiNg.

> Dalle3 is supported in this fork: https://github.com/lofcz/OpenAiNg

**Comment by lofcz** [comment]
I'm sorry to hear that, to support Dalle3 upstream, you can do the following:

1. Fork OpenAI-API-dotnet
2. Copy & paste the following changes, these are all compatible with the original database:
2. https://github.com/lofcz/OpenAiNg/commit/fb208ab37cbde43f4ddbb5e0e5cc4c152797d2cb
3. https://github.com/lofcz/OpenAiNg/commit/936dcabc2e3f07c74fa9522eda059259bf65daf9
4. https://github.com/lofcz/OpenAiNg/commit/184465a858d5ee47ebd7eebc2b0de0d144a4782f

Hope this helps.

**Comment by elango-kamatchi** [comment]
Thank you lofcz.

**Comment by VinceGsm** [comment]
Hello @lofcz , i have the same question this issue have. 
With OpenAiNg, how can you choose between Dall-E v2 and v3 (not v3 HD) or does it automatically consume the v3 ?

**Comment by lofcz** [comment]
In OpenAiNg just provided either Dalle2 or Dalle3 as the model in the ImageaGeberate request. HD needs to be toggled on manually as another argument.

**Comment by VinceGsm** [comment]
**Many thanks** @lofcz 
OpenAiNg is exactly what I was looking for.
Have a great day !
