### ISSUE TITLE
Error converting value "gpt-3.5-turbo-0613" to type 'OpenAI_API.Models.Model

### ISSUE THREAD

**Issue by DmitryBorodiy** [OkGoDoIt/OpenAI-API-dotnet#183]
Error converting value "gpt-3.5-turbo-0613" to type 'OpenAI_API.Models.Model'. Path 'model', line 5, position 31. I have no idea how I can fix this exception.

**Comment by OkGoDoIt** [comment]
Hmm, can you give me some more context about where this is coming from?  Also I just pushed a new version 1.8 with support for additional models, so maybe try that?

**Comment by DmitryBorodiy** [comment]
It's happens only when I build UWP app with .NET Native.

**Comment by OkGoDoIt** [comment]
Perhaps you're somehow using a different JSON deserializer? The Model type is strongly typed but it has an implicit conversion from a string, so when parsing a JSON reply from the API it should converted implicitly. It sounds like that might not be happening for some reason.

But I'm just guessing, perhaps you can give me a more detailed stack trace so I can understand where this is happening?

I'm actually not familiar with .net native and it's not a scenario I have tested, maybe you can give me some more details about your setup so I can try it myself.
