### ISSUE TITLE
Davinci-2 support?

### ISSUE THREAD

**Issue by ecsplendid** [OkGoDoIt/OpenAI-API-dotnet#19]
Pretty sure it's not leveraging the new model right?

**Comment by kinetiq** [comment]
@WilliamWelsh @OkGoDoIt  If that's the case, please make it easier to figure that out and direct people to a more current resource. This one implements obsolete APIs like Engine, and will eventually stop working, also the inability to use the most current engine caused me a lot of confusion today, I spent  hours trying to figure out the problem.

As it stands, this library gets the lion's share of the traffic while this one is actually much more current: https://github.com/betalgo/openai

**Comment by LarsLiden** [comment]
You can also pass in the string:

new OpenAI_API.OpenAIAPI(apiKey, "text-davinci-002");

**Comment by gotmike** [comment]
should support the latest models as of this commit: https://github.com/OkGoDoIt/OpenAI-API-dotnet/commit/f4d9d9d1b9885176948967f21074ad1ebe00331a
