### ISSUE TITLE
 The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing

### ISSUE THREAD

**Issue by renewtx** [OkGoDoIt/OpenAI-API-dotnet#212]
Wondering if anyone can help me on this ... I am working on a PowerShell script that queries the M365 PowerAutomate flow environment to find instances of flows that have failed.  A while back when I first started with this I encountered this error:
![image](https://github.com/OkGoDoIt/OpenAI-API-dotnet/assets/58831734/f3986372-956a-4ef2-bb1d-b59acd2a1d53)

I also tried the same code running in PowerShell on a workstation, and there I got this error:
![image](https://github.com/OkGoDoIt/OpenAI-API-dotnet/assets/58831734/a06dbdf3-9742-4e08-9d82-4bafe676e6dc)

After lots of googling I was able to find a post on GitHub that referenced a bug discovered late last year and which was fixed in the PnP.PowerShell v2.4.13-nightly release.  At the time I was able to download that release and test it in both the Azure runbook and on the workstation, and it fix the issue.

However, I am now trying to deploy this code on a server where I had to update PowerShell (I installed 2.4.60-nightly which appears to be the latest (I tried pulling v2.4.13 but that does not appear to be available).  When I now run my code I am back to getting the error 

The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.

Anyone know how to resolve this?  Is the original bug back in the current version?  Thoughts?  Ideas?

Thanks

**Comment by OkGoDoIt** [comment]
You can override the HttpClient in order to adjust the timeout.  Details at https://github.com/OkGoDoIt/OpenAI-API-dotnet?tab=readme-ov-file#ihttpclientfactory and in #103
