### ISSUE TITLE
Is the playground system available?

### ISSUE THREAD

**Issue by Pronner** [OkGoDoIt/OpenAI-API-dotnet#26]
Does that exist? Is there like an engine that uses the playground system or does whatever you want (text-wise)

e.g. The request is "Write a random essay for me". 

I'm new to OpenAI, so I'm not sure what it's called and if you added it or not.

**Comment by gotmike** [comment]
not sure this is a code/repo/sdk question? the playground is a diff animal altogether, although should produce the same results as we do via API.
