### ISSUE TITLE
URL difference?

### ISSUE THREAD

**Issue by securigy** [OkGoDoIt/OpenAI-API-dotnet#29]
Maybe I do not understand something, but I look at the library API and its URLSs, and I also tried them and they work:
$"https://api.openai.com/v1/engines/{Api.EngineName}/completions"
where {Api.EngineName} is the model name.

and I also look at the OpenAI documentation (below) and they are **different**...
Can you explain?

https://api.openai.com/v1/completions

or in curl:
curl https://api.openai.com/v1/completions \
  -H 'Content-Type: application/json' \
  -H 'Authorization: Bearer YOUR_API_KEY' \
  -d '{
  "model": "text-davinci-003",
  "prompt": "Say this is a test",
  "max_tokens": 7,
  "temperature": 0
}'

**Comment by OkGoDoIt** [comment]
The `https://api.openai.com/v1/engines/{Api.EngineName}/completions` style endpoint URL is from the original API release.  I have updated this to the current format of `https://api.openai.com/v1/completions` in the latest release. See https://github.com/OkGoDoIt/OpenAI-API-dotnet/commit/f4d9d9d1b9885176948967f21074ad1ebe00331a.  As long as you're using the latest release (1.3 on NuGet), this should be fixed.

Are you finding this problem still persisting?  Did I miss an instance of changing the URL somewhere?

**Comment by securigy** [comment]
Well, I downloaded it with NuGet about 4 weeks ago and now can not update it: I had to do some customization to fit my needs like CancellationToken in order to be able to abort long async operations (although I realize it will not always work), and some other things like removing APIs that are not compliant with .NET Framework - my project is not .NET Core since it is Add-In/Plugin to existing app.

The question is whether one way is more beneficial that other? or both gets to the same endpoint in the server?

**Comment by OkGoDoIt** [comment]
The `https://api.openai.com/v1/engines/{Api.EngineName}/completions` style endpoint URL no longer works, it will result in an error.  You need to use the `https://api.openai.com/v1/completions` endpoint and pass the model as a parameter, as in the OpenAI documentation you cited.

See https://github.com/OkGoDoIt/OpenAI-API-dotnet/commit/f4d9d9d1b9885176948967f21074ad1ebe00331a?diff=unified#diff-477a1379aece5a9c89ccfdf3099e6a3764c908ba87cae94cd85b7db198aace16R57 for how the updated version works.  You may need to patch your local code with the changes in https://github.com/OkGoDoIt/OpenAI-API-dotnet/commit/f4d9d9d1b9885176948967f21074ad1ebe00331a to get it working.

Sorry for the hassle, but OpenAI has been changing their API definition over time and as API consumers we have to make these changes to be able to continue to work.

**Comment by gotmike** [comment]
closing this issue as it seems resolved. LMK if you need to discuss further.
