### ISSUE TITLE
latest release showing v1.2 instead of v1.3 on github

### ISSUE THREAD

**Issue by gotmike** [OkGoDoIt/OpenAI-API-dotnet#30]
i notice that the latest release on github is v1.2, but i have seen in issues/discussions that we are talking about v1.3.

do we need to have a new release?

also: i have been idle for a while, happy to jump in and help wrap up some of these issues. please bear with me.

**Comment by gotmike** [comment]
i believe you said you need to do this on your local computer...

**Comment by OkGoDoIt** [comment]
I pushed the updated v1.3 to nuget, but forgot to also release here on GitHub.  Fixed now.
