### ISSUE TITLE
API Key Validation

### ISSUE THREAD

**Issue by securigy** [OkGoDoIt/OpenAI-API-dotnet#37]
How do you validate the key? I'd rather not call API and generate the text and discard it just to validate the key...
Using fake key, for example "1234" produces some weird errors...

Any ideas?

**Comment by OkGoDoIt** [comment]
In theory we could do some format checking on the client side but that
would just be based on assumptions about what the key looks like.
Realistically, only OpenAI can tell you if the key is valid, so you’re
going to have to call the API. You could call the models endpoint which
doesn’t count for billing.

Sounds like we could be better about error messaging in the case of an
invalid key though. It’s definitely worth working on better error handling
in this case.

**Comment by gotmike** [comment]
i think listing the models would not incur a charge, but would require a valid api key to authenticate.

in this repo, use like this test...
https://github.com/OkGoDoIt/OpenAI-API-dotnet/blob/52c230c340ffc70c67e727ec5c0c5ed84c70d435/OpenAI_Tests/ModelEndpointTests.cs#L24

but we could add an api validation method?

**Comment by OkGoDoIt** [comment]
I've implemented this in https://github.com/OkGoDoIt/OpenAI-API-dotnet/commit/0876a1564ae2b3274b742986807309b62af21144
You can now call `ValidateAPIKey()` on any APIAuthentication object.  So for example:

```csharp
OpenAIAPI api = new OpenAIAPI("YOUR_API_KEY");
api.Auth.ValidateAPIKey(); //returns true if the api key is valid, or false if empty or not accepted by the OpenAI API
```
