### ISSUE TITLE
Doesn't seem very reliable, in Unity?

### ISSUE THREAD

**Issue by hughperkins** [OkGoDoIt/OpenAI-API-dotnet#39]
Easy to use. Looks great. When it works, it's great :) However, I find it only succeeds about 30% of the time, for completions. The other 70% of the time, there's no return, and no error.

It's not my network or api key, since if I use my own code to call openapi api, I get 100% successful returns.

Example code I'm using for your API:
```
        OpenAIAPI api = new OpenAIAPI(Auth.openai_api_key);
        CompletionRequest completionRequest = new CompletionRequest{
            Prompt = "Q: Hi, how are you? A: ",
            Model = "text-davinci-003",
            MaxTokens = 256,
            Temperature = 0.7f,
            Echo = true
        };

        if(true) {
            // non-streaming
            CompletionResult result = await api.Completions.CreateCompletionAsync(completionRequest);
            Debug.Log(result.ToString());
        }

        if(false) {
        // streaming
        Debug.Log("calling openapi...");
        await api.Completions.StreamCompletionAsync(
            completionRequest,
            result => {
                try {
                    Debug.Log($"result to string{result.ToString()}");
                } catch(Exception e) {
                    Debug.Log($"exception {e.ToString()}");
                }
        });
        }
```

**Comment by hughperkins** [comment]
(I'm running in Unity 2021, .Net Standard 2.1, on a Mac Silicon, using your version 1.4)

**Comment by hughperkins** [comment]
Note: looks like it works fine from commandline, but not from Unity. Hmmm. Pondering :)

**Comment by hughperkins** [comment]
I'll dig a little, and re-open if I narrow it down a little more...

**Comment by gotmike** [comment]
Ok sure. If u can narrow it down happy to help.

**Comment by hughperkins** [comment]
Ok, I foudn that the problem was that for some reason Unity doesn't display the exceptions coming out of calls into this library. I'm not sure why. But wrapping calls with a try...catch, and printing the exception myself, displays hte exception correctly

```
            CompletionResult result = await api.Completions.CreateCompletionAsync(completionRequest);
            Debug.Log(result.ToString());
            } catch(Exception e ) {
                Debug.Log("exception callling completionasync");
                Debug.Log(e.ToString());
            }
```

Result:

<img width="981" alt="Screen Shot 2023-02-09 at 06 50 34" src="https://user-images.githubusercontent.com/123560/217805176-36aaf643-155d-4336-b5fc-6266425870ab.png">

**Comment by hughperkins** [comment]
So, it turns out that there was actually a partial davinci003 outage yesterday, so just bursting with one or two completion requests caused TooManyRequests errors. So it was a coincidence between trying your library, and the outage :)

**Comment by hughperkins** [comment]
PS Cool library. Thank you for building this :)

**Comment by gotmike** [comment]
oh, that's interesting. so is there an issue to debug related to the library connecting to unity?

**Comment by hughperkins** [comment]
Nope. Your library works great. Thank you :)
