### ISSUE TITLE
HttpClient created that is never used

### ISSUE THREAD

**Issue by KeithHenry** [OkGoDoIt/OpenAI-API-dotnet#43]
Here:
https://github.com/OkGoDoIt/OpenAI-API-dotnet/blob/97fb71b7690c2e3b763ae45b1cc02b2133bb3e55/OpenAI_API/Files/FilesEndpoint.cs#L74

**Comment by OkGoDoIt** [comment]
Thanks!  Fixed in https://github.com/OkGoDoIt/OpenAI-API-dotnet/commit/7755f4ceb08255ff5084b804184a476dd0dac050
