### ISSUE TITLE
Create interfaces for the OpenAIAPI and the Endpoints

### ISSUE THREAD

**Issue by pandapknaepel** [OkGoDoIt/OpenAI-API-dotnet#49]
With interfaces u can use moq to create (or generate 😄) unit tests.
Also think about to create an config object for the api key, so that it can be added to the di.
And an extension method to add the api client to the di would be nice.
And the naming should be OpenAiApi, or not?

**Comment by KeithHenry** [comment]
Microsoft naming convention is 2 letter acronyms in capitals, 3 or more letter acronyms only the first letter capitalised, so it would be `OpenAIApi` for consistency with .NET

However, `Api` is tautologous here, we don't need it, so if I was going to break backwards compatibility with a naming change it would be to just `OpenAI`.
