### ISSUE TITLE
Support for Chat Completions

### ISSUE THREAD

**Issue by rsthn** [OkGoDoIt/OpenAI-API-dotnet#54]
Today chat completions are now available:
https://platform.openai.com/docs/api-reference/chat/create

Uses a new end-point (https://api.openai.com/v1/chat/completions), and the latest model "gpt-3.5-turbo".

**Comment by megalon** [comment]
I am taking a stab at this, but I've hit a wall.
The API is throwing an error that the endpoint is incorrect, but it looks right to me.
```
System.Net.Http.HttpRequestException: Error at chat/completions (https://api.openai.com/v1/chat/completions) with HTTP status code: NotFound. Content: {
  "error": {
    "message": "Invalid URL (POST /v1/chat/completions)",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}
```

Anybody have any suggestions for why this might be happening?
I am not very familiar with how APIs work to be honest.

Here are my changes so far
<https://github.com/OkGoDoIt/OpenAI-API-dotnet/compare/master...megalon:OpenAI-API-dotnet:feature/chat>

**Comment by davidyack** [comment]
@megalon confirming your changes worked for me

**Comment by rsthn** [comment]
This is awesome! Thank you @megalon

**Comment by mairura** [comment]
![Screenshot from 2023-03-02 09-01-36](https://user-images.githubusercontent.com/73795624/222344410-7bff4f7f-1ffd-41b3-a615-2d5b6b133b47.png)

**Comment by dexinhuang** [comment]
Can someone provide an example of calling the new ChatGPT completion? 
I used to use this code, `                var c = new CompletionRequest(memory.ToString(), GetModel(model), MaxTokens, Temperature, null, Top_p, NumOutputs, PresencePenalty, FrequencyPenalty, LogProbs,null, StopSequences);
                var results = await OAIEngine.Instance.Api.Completions.CreateCompletionsAsync(c);` And I'm not sure how to achieve the same results in the new format

**Comment by rsthn** [comment]
For testing I'm currently using:

```javascript
var req = new OpenAI_API.Chat.ChatRequest();
req.Model = OpenAI_API.Models.Model.ChatGPTTurbo;
req.Messages = new System.Collections.Generic.List<OpenAI_API.Chat.ChatMessage>();
req.Messages.Add(new OpenAI_API.Chat.ChatMessage("user", "Give me a list of 10 colors"));
req.Temperature = 0;
req.MaxTokens = 100;

var result = await client.Chat.CreateChatAsync(req);
foreach (var i in result.Choices)
{
    Console.WriteLine("["+i.FinishReason+"] " + i.Message.Role + " => " + i.Message.Content);
}
```

**Comment by dexinhuang** [comment]
Amazing, thanks!

**Comment by dexinhuang** [comment]
Quick question, I'm being charged for gpt-3.5-turbo-0301, but I've even removed the model from the model list. Is anyone else running into the same issue?

**Comment by megalon** [comment]
gpt-3.5-turbo-0301 is the only "chat" model available from the OpenAi API
right now.

gpt-3.5-turbo uses the latest model, and since 0301 is the only model
available, that's the one it uses.

"Developers who use the gpt-3.5-turbo model will always get our recommended
stable model, while still having the flexibility to opt for a specific
model version. For example, today we’re releasing gpt-3.5-turbo-0301, which
will be supported through at least June 1st, and we’ll update gpt-3.5-turbo
to a new stable release in April."

https://openai.com/blog/introducing-chatgpt-and-whisper-apis

If you want to use a different model like davinci, you need to use the old
"completions" API endpoint

**Comment by slothful0928** [comment]
Great! I appreciate the information!

**Comment by dexinhuang** [comment]
Great! I appreciate the information! Thanks!

**Comment by ericliu0408** [comment]
Could you advise that when it could  come out?
