### ISSUE TITLE
File Upload for Fine Tuning Not Working

### ISSUE THREAD

**Issue by dano1066** [OkGoDoIt/OpenAI-API-dotnet#59]
I have installed this via nuget and its using v 1.5.0.

I have created a fine tune file with the following line 

`{"prompt": "test", "completion": "test 123"}`

I am uploading it with the following

`var response = await api.Files.UploadFileAsync("fine-tune.jsonl");`

When the code runs, I get the following error

```
Error at files (https://api.openai.com/v1/files) with HTTP status code: BadRequest. Content: {
  "error": {
    "message": "Expected file to have JSONL format, where every line is a JSON dictionary. Line 1 is not a dictionary (HINT: line starts with: \"﻿{\"p...\").",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}
```

**Comment by Tronald** [comment]
I am having the same issue. You ever figure this out?

**Comment by Tronald** [comment]
Ok I actually downloaded the file itself (vs just copying the JSON, and then I manually included the "fine-tune" specification in the `UploadFileAsync(file, prompt)` call and it magically worked. 

I wonder if ChatGPT is finnicky on the file's encoding?

**Comment by DajShung** [comment]
Make sure you're using JSONL and not JSON. 
JSONL is a different format. Also, make sure you're using the keywords 'prompt' and 'completion'. This is a working example:

{"prompt":"Wat is de leukste stad van Belgie?","completion":"Roeselare"}
{"prompt":"Wat is het hoogste punt in Roeselare","completion":"Hotel De Bonte Os is het hoogste punt in Roeselare"}
{"prompt":"Wat staat er bovenop De Bonte Os?","completion":"Bovenop De Bonte Os staan grote verlichte letters."}
{"prompt":"Wat staat er op die letters?","completion":"Die letters tonen 'Tower & Hotel'."}
{"prompt":"Wie doet je de groeten?","completion":"Jurn"}

**Comment by dano1066** [comment]
I was able to solve the issue. It was an encoding thing. I used notepad++ to go with UTF-8 instead of UTF-8 BOM
