### ISSUE TITLE
Beta Instruct

### ISSUE THREAD

**Issue by mdgibbons** [OkGoDoIt/OpenAI-API-dotnet#6]
I see there is already a pull request to add the beta-instruct engines.  Is this ready to commit/implement?  I am looking to use that functionality.

**Comment by gotmike** [comment]
seems like the models are updated to the latest in: https://github.com/OkGoDoIt/OpenAI-API-dotnet/commit/f4d9d9d1b9885176948967f21074ad1ebe00331a
