### ISSUE TITLE
Whitespace optional in SSE event format

### ISSUE THREAD

**Issue by KeithHenry** [OkGoDoIt/OpenAI-API-dotnet#60]
GPT used the server-side-events format to send streamed completions https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#event_stream_format

Currently the `data: ` prefix is treated as optional, but any line without it should be ignored, and in particular any line starting with just `:` should be a comment.

Also the space should be optional, both `data: ` and `data:` should work. 

https://github.com/OkGoDoIt/OpenAI-API-dotnet/blob/e949bd409e5fb793071a2adbf5b8c35270f97fd3/OpenAI_API/EndpointBase.cs#L372-L373

**Comment by OkGoDoIt** [comment]
Thanks @KeithHenry.  I was not familiar with this format so I followed the OpenAI documentation literally.  I have fixed this in 30aca80fe0a6d04f01353ac730f058b3930c3099
