### ISSUE TITLE
I am looking forward to your works based on GPT-3.5-Turbo.

### ISSUE THREAD

**Issue by Lenloo** [OkGoDoIt/OpenAI-API-dotnet#63]
You have done a great job, and we hope you can quickly release works based on GPT-3.5-Turbo!

**Comment by ajaustin12** [comment]
Megalon got the chat request endpoint working here: https://github.com/OkGoDoIt/OpenAI-API-dotnet/issues/54

Check it out!

**Comment by OkGoDoIt** [comment]
This is complete from #56 and #67 and will be included in the v1.6 release on Nuget
