### ISSUE TITLE
Endpoint Properties in IOpenAIAPI interface

### ISSUE THREAD

**Issue by pandapknaepel** [OkGoDoIt/OpenAI-API-dotnet#68]
I have made an error in the IOpenAIAPI interface (and the OpenAIAPI class). The endpoint properties should be defined as interfaces instead of classes so that they are also suitable for Moq tests. Additionally, the IChatEndpoint interface should be added as a property.

Wrong:
~~~c#
CompletionEndpoint Completions { get; }
~~~~

Correct:
~~~c#
ICompletionEndpoint Completions { get; }
~~~

**Comment by pandapknaepel** [comment]
These are good ideas that apply to the project in general. A separate ticket could certainly be created for this. My interest in this ticket is only to be able to test services with Moq that use this NuGet package. I am not the developer of the package. 
That's why I tried not to include any breaking changes, etc. in my PR.

**Comment by Baklap4** [comment]
Agreed to hit those refactors off in another ticket
