### ISSUE TITLE
Cant install

### ISSUE THREAD

**Issue by JanLangeDK** [OkGoDoIt/OpenAI-API-dotnet#70]
I get these error when running Install-Package OpenAI:

Install-Package : NU1108: Cycle detected. 
  OpenAI -> OpenAI (>= 1.6.0).
At line:1 char:1
+ Install-Package OpenAI
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Install-Package : Package restore failed. Rolling back package changes for 'OpenAI'.
At line:1 char:1
+ Install-Package OpenAI
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand

**Comment by NyasakiAT** [comment]
So, what were the issue? Experiencing the same issue right now

**Comment by OqilovSherzod** [comment]
Change your project name, assuming your project name is exact same with this package (OpenAI)
