### ISSUE TITLE
Completions, in my case, is not working..

### ISSUE THREAD

**Issue by arilishu** [OkGoDoIt/OpenAI-API-dotnet#9]
My use case is based on an example, repeated on a new text. It's working by CURL, but not using the method:
`var results = api.Completions.CreateCompletionsAsync(new CompletionRequest(body
                    , temperature: 0, max_tokens: 250, top_p: 1), 1).Result;`

this is the body:
get some information from this text on a list.
###
[Text1]lorem ipsum...
---
[List1]
name: John
Last: Doe
Age: 100
Date of birth: 1900/01/01

###
[Text2] {new text added dynamicaly}
--- 
[List2]
name:

and that's what I am waiting.. the competition of that List2.
It's working on the playground, it's working by CURL.
It's not working using your method..
The response is the same text as List1:
`name: John
Last: Doe
Age: 100
Date of birth: 1900/01/01`
Any suggestion?
Welcome to work with you to solve this.

Thanks!

**Comment by gotmike** [comment]
seems like yes there are some differences from the playground. i'm testing it...

**Comment by gotmike** [comment]
closing this for now, i think it is in fact a prompt/temp issue if you are looking for diff results.
